source/Notification/urls.py
from django.conf.urls import url
from source.Notification import views

app_name = "notification"

urlpatterns = [
    url(r'create/$', views.CreateNotificationView, name="CreateNotification"),
]

source/Notification_System/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from source.accounts import urls as accounts_urls
from source.query import urls as query_urls
from source.Notification import urls as notification_urls


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^query/', include(query_urls)),
    url(r'^notification/', include(notification_urls)),
    url(r'^main/$', TemplateView.as_view(template_name='accounts/main.html'), name='main'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name="contact"),
    url(r'^about/$', TemplateView.as_view(template_name='About.html'), name="about"),

    ]

source/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'login/$', views.LoginView , name="login"),
    url(r'signup/$', views.SignUpView , name="signup"),
    url(r'profile/$', views.ProfileView , name="profile"),
    url(r'logout/$', views.LogoutView , name="logout"),
]

source/query/urls.py
from django.conf.urls import url
from source.query.views import QuestionHandlingView, AnswerHandlingView

app_name = "query"

urlpatterns = [
    url(r'ask/$' , QuestionHandlingView, name="QuestionAsk"),
    url(r'answer/$' , AnswerHandlingView, name="QuestionAnswer")
]

source/accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from .models import Student, Faculty, FacultyCourse, StudentCourse


class SignUpStudentForm(forms.ModelForm):

    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        exclude = ('User',)
        model = Student

    def clean(self):

        # print(self.cleaned_data)
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        StudentID = self.cleaned_data['StudentID']

        if StudentID:

            try:
                Student.objects.get(StudentID=StudentID)
                raise ValidationError("Student ID already exists!", code="ID error")

            except ObjectDoesNotExist:
                pass

            if 16101000 < int(StudentID) < 16108999:
                pass
            else:
                raise ValidationError("Student ID is no valid. Make sure it is correct", code="ID error")

        if password1 and password2:

            if password1 != password2:
                raise ValidationError("Make Sure both passwords are same", code="Password doesn't match")

            return self.cleaned_data


class SignUpFacultyForm(forms.ModelForm):

    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        exclude = ('User',)
        model = Faculty

    def clean(self):

        # print(self.cleaned_data)
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2:

            if password1 != password2:
                raise ValidationError("Make Sure both passwords are same", code="Password doesn't match")

            return self.cleaned_data


class FacultyCoursesForm(forms.ModelForm):

    class Meta:
        model = FacultyCourse
        fields = ['Course', 'Semester']

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        self.fields['Course'].widget.attrs['class'] = "browser-default"


class StudentCoursesForm(forms.ModelForm):

    class Meta:
        model = StudentCourse
        fields = ['Course', 'Semester']

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        self.fields['Course'].widget.attrs['class'] = "browser-default"

source/accounts/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.middleware import get_user
from django.contrib.auth.models import User
from django.contrib.auth.views import logout
from django.shortcuts import render, redirect
from source.Notification.models import Message
from source.accounts.forms import SignUpStudentForm, SignUpFacultyForm, FacultyCoursesForm, StudentCoursesForm
from source.accounts.models import Student, Faculty
from django.http import JsonResponse
from source.query.models import Question, Answer


def LoginView(request):


    if request.method == "POST" and request.is_ajax():

        form = AuthenticationForm(data=request.POST)

        if form.is_valid():

            if request.POST['action'] == "student":

                user = form.get_user()

                if Student.objects.filter(User__exact=user).exists():

                    login(request, user)
                    request.session['user'] = 'student'
                    request.session['username'] = user.username

                    return JsonResponse({"response": 'You are logged in Student', "working":"yes"})

                response = "It seems you are authenticated as Staff Member.Kindly login from Staff Section"

            else:

                user = form.get_user()

                if Faculty.objects.filter(User__exact=user).exists():

                    login(request, user)
                    request.session['user'] = 'staff'
                    request.session['username'] = user.username
                    return JsonResponse({"response": 'You are logged in Staff'})

                response = "It seems you are authenticated as Student Member.Kindly login from Student Section"

        if form.errors:
            return JsonResponse({"response": '''Please enter a correct username and password''', "working":"no" })
        else:
            return JsonResponse({"response": response, "working":"no"})


    try:
        ID = request.session['username']
    except:
        ID = None

    if ID:
         return redirect('accounts:profile')

    return render(request, 'accounts/loginForm.html', {})


def SignUpView(request):

    if request.method == "POST":

        if request.POST['action'] == "student":

            form = SignUpStudentForm(request.POST)

            if form.is_valid():

                instance = form.save(commit=False)

                username = form.cleaned_data.get('StudentID')
                password = form.cleaned_data.get('password')

                user = User.objects.create_user(username=username)
                user.set_password(password)
                user.save()

                instance.User = user
                instance.save()

                # Adding Student to respective group
                instance.add_into_group()

                if user.is_authenticated():
                    request.session['user'] = 'student'
                    request.session['username'] = instance.StudentID
                    login(request, user)

                return redirect('main')

            else:

                context = {}
                if form.errors:
                    context = {
                        "errors":form.errors
                    }

                return render(request, 'accounts/signupForm.html', context)

        else:

            form = SignUpFacultyForm(request.POST)

            if form.is_valid():

                instance = form.save(commit=False)

                username = form.cleaned_data.get('FacultyID')
                password = form.cleaned_data.get('password')

                user = User.objects.create_user(username=username)
                user.set_password(password)
                user.save()

                instance.User = user
                instance.save()

                # Adding Faculty to Fac group
                instance.add_into_group()

                if user.is_authenticated():
                    request.session['user'] = 'staff'
                    request.session['username'] = instance.FacultyID
                    login(request, user)

                return redirect('main')

            else:

                context = {}
                if form.errors:
                    context = {
                        "errors": form.errors
                    }

                return render(request, 'accounts/signupForm.html', context)

    else:

        return render(request, 'accounts/signupForm.html', {})


@login_required()
def ProfileView(request):

    ID = request.session['username']
    user_type = request.session['user']

    if user_type == 'student':

        object = Student.objects.get(StudentID__exact=ID)
        all_groups = request.user.groups.all()
        all_messages = Message.objects.filter(SentFor__in=all_groups).order_by('-DateTime')[:6]
        form = StudentCoursesForm()
        all_teachers = Faculty.objects.filter(Courses__faculty__Courses__in=object.Courses.all()).distinct()
        Responses = Answer.objects.filter(Question__QueriedBy=ID).filter(Question__IsAnswered=True).order_by('-AnsweredAt')

        context = {
            "object": object,
            "all_messages": all_messages,
            "form": form,
            "all_teachers":all_teachers,
            "Responses": Responses,
        }

        return render(request, 'accounts/Student_Home.html', context)

    elif user_type == 'staff':
        object = Faculty.objects.get(FacultyID__exact=ID)
        all_messages = Message.objects.filter(SentBy__exact=request.user).order_by('-DateTime')[:6]
        form = FacultyCoursesForm()
        Questions = Question.objects.filter(CreatedFor__exact=get_user(request)).filter(IsAnswered=False)

        context = {
            "object":object,
            "all_messages":all_messages,
            "form":form,
            "Questions":Questions,
        }

        return render(request, 'accounts/Faculty_Home.html', context)


@login_required()
def LogoutView(request):

    logout(request)
    return redirect('accounts:login')

source/templates/accounts/Faculty_Home.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/facultyhome.css' %}">

    <script>
          $(document).ready(function(){
            $('.modal').modal();
            });

          $(document).ready(function(){
            $('.tooltipped').tooltip();
          });

     $(document).ready(function(){
        $('select').material_select();
      });
    </script>

{% endblock %}


{% block main %}


        <div class="container">

          <div id="profile-page" class="section">

            <div id="profile-page-header" class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="{% static 'Images/user-profile-bg.jpg' %}" alt="user background">
                </div>
                <figure class="card-profile-image">
                    <img src="{% static 'Images/img_6.jpg' %}" alt="profile image" class="circle z-depth-2 responsive-img activator">
                </figure>
                <div class="card-content">
                  <div class="row">
                    <div class="col s3 offset-s2">
                        <h4 class="card-title grey-text text-darken-4">{{ object.Name }}</h4>
                        <p class="medium-small grey-text">{{ object.get_designation_display }}</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ object.FacultyID }}</h4>
                        <p class="medium-small grey-text">ID</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ object.get_department_display }} Engineering</h4>
                        <p class="medium-small grey-text">Department</p>
                    </div>

                    <div class="col right">
                        <a href="{% url 'notification:CreateNotification' %}" class="btn orange waves-yellow waves-effect">Create or Schedule Message </a>

                        <p class="center-align"><span class="material-icons medium">mail_outline</span></p>
                    </div>
                  </div>
                </div>
            </div>

            <div id="profile-page-content" class="row">

              <div id="profile-page-sidebar" class="col s12 m4">

              <!-- Modal Trigger -->
              <a class="tooltipped waves-effect waves-light orange btn large modal-trigger btn-floating" data-position="right" data-tooltip="Set Up the Courses" href="#modal1"><i class="material-icons">settings</i></a>

                <!-- Profile About  -->
                <div class="card light-blue">
                  <div class="card-content white-text">
                    <span class="card-title">About Me!</span>
                    <p>Something About Staff</p>
                  </div>
                </div>
                <!-- Profile About  -->

                <!-- Profile About Details  -->
                <ul id="profile-page-about-details" class="collection z-depth-1">
                  <li class="collection-item">
                    <div class="row">
                      <div class="col s5 grey-text darken-1"><i class="mdi-action-wallet-travel"></i> E-mail</div>
                      <div class="col s7 grey-text text-darken-4 right-align">{{ object.Email }}</div>
                    </div>
                  </li>
                  <li class="collection-item">
                    <div class="row">
                      <div class="col s5 grey-text darken-1"><i class="mdi-social-poll"></i> Contact Number</div>
                      <div class="col s7 grey-text text-darken-4 right-align">{{ object.ContactNumber }}</div>
                    </div>
                  </li>

                </ul>
                <!--/ Profile About Details  -->


                <ul id="task-card" class="collection with-header">
                  <li class="collection-header orange">
                      <h4 class="task-card-title">Recent Notifications Sent</h4>
                  </li>
                    {% for message in all_messages %}
                  <li class="collection-item ">
                      <input type="checkbox" id="task1" />
                      <label class="truncate" for="task1">{{ message.title }} <a href="#" class="secondary-content"><span class="ultra-small">{{ message.DateTime|timesince }}</span></a>
                      </label>
                  </li>
                    {% endfor %}

                </ul>

                <!-- task-card -->
                <ul id="task-card" class="collection with-header">
                  <li class="collection-header cyan">
                      <h4 class="task-card-title">My Task <a href="#" class="small white-text right">Add Task</a> </h4>
                      <p class="task-card-date">Date</p>
                  </li>
                  <li class="collection-item dismissable">
                      <input type="checkbox" id="task1" />
                      <label for="task1">Task1 <a href="#" class="secondary-content"><span class="ultra-small">Today</span></a>
                      </label>
                      <span class="task-cat teal">Tag</span>
                  </li>

                </ul>
                <!-- task-card -->

              </div>


                <!-- profile-page-wall -->
              <div id="profile-page-wall" class="col s12 m8">

                <!-- profile-page-wall-posts -->
                <div id="profile-page-wall-posts" class="row">
                  <div class="col s12">

                      <h3 class="light-blue-text">Queries</h3>
                      <!-- post here -->

                  {% if Questions %}
                      {% for question in Questions %}
                      <div id="profile-page-wall-post" class="card">


                        <div class="card-profile-title">
                          <div class="row">
                            <div class="col s1">
                              <img src="{% static 'Images/profile.png' %}" alt="" class="circle responsive-img valign profile-post-uer-image">
                            </div>
                            <div class="col s10">
                              <p class="grey-text text-darken-4 margin">{{ question.QueriedBy }}</p>
                              <span class="grey-text text-darken-1 ultra-small">{{ question.AskedAt }}</span>
                            </div>
                            <div class="col s1 right-align">
                              <i class="mdi-navigation-expand-more"></i>
                            </div>
                          </div>
                        <form method="post" action="{% url 'query:QuestionAnswer' %}">
                            {% csrf_token %}
                        <div class="card-content">
                          <p>{{ question.QuestionTitle }}</p>
                        </div>

                            <input type="hidden" name="pk" value="{{ question.pk }}">
                        <div class="card-action row">

                          <div class="input-field col s8 margin" >
                            <input id="profile-comments" type="text" class="validate margin" name="AnswerTitle">
                            <label for="profile-comments" class="">Answer</label>
                          </div>

                            <button class="btn waves-teal waves-effect right" type="submit">Answer</button>
                        </div>
                            </form>
                      </div>
                  </div>

                      {% endfor %}

                      {% else %}
                      <h6>No Queries Yet</h6>
                  {% endif %}

                      <!--/post here -->

                </div>
                <!--/ profile-page-wall-posts -->

              </div>
              <!--/ profile-page-wall -->

            </div>


          </div>

          </div>

       </div>

        <!-- Modal Structure -->
        <div id="modal1" class="modal">
            <div class="modal-content">
              <h4>FILL THE COURSES YOU TEACH</h4>
                <form>
                    {{ form.as_p }}
                </form>
            <div class="modal-footer">
              <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
        </div>
        </div>




{% endblock %}

source/templates/accounts/Student_Home.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block style %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/studenthome.css' %}">


    <script>
        $(document).ready(function(){
            $('.modal').modal();
            });

          $(document).ready(function(){
            $('.tooltipped').tooltip();
          });
    </script>

{% endblock %}


{% block main %}


        <div class="container">

          <div id="profile-page" class="section">

            <div id="profile-page-header" class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="{% static 'Images/user-profile-bg.jpg' %}" alt="user background">
                </div>
                <figure class="card-profile-image">
                    <img src="{% static 'Images/profile.png' %}" alt="profile image" class="circle z-depth-2 responsive-img activator">
                </figure>
                <div class="card-content">
                  <div class="row">
                    <div class="col s3 offset-s2">
                        <h4 class="card-title grey-text text-darken-4">{{ object.Name }}</h4>
                        <p class="medium-small grey-text">Student</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ object.StudentID }}</h4>
                        <p class="medium-small grey-text">ID</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ object.get_branch_display }}</h4>
                        <p class="medium-small grey-text">Department</p>
                    </div>
                    <div class="col s2 center-align">
                        <h4 class="card-title grey-text text-darken-4">{{ object.YearOfStudy|ordinal }}</h4>
                        <p class="medium-small grey-text">Year</p>
                    </div>
                  </div>
                </div>
            </div>

            <div id="profile-page-content" class="row">

              <div id="profile-page-sidebar" class="col s12 m4">

              <!-- Modal Trigger -->
              <a class="tooltipped waves-effect waves-light btn orange modal-trigger" data-position="right" data-tooltip="Set Up the Courses" href="#modal1"><i class="material-icons">settings</i></a>
                <!-- Profile About  -->
                <div class="card light-blue">
                  <div class="card-content white-text">
                    <span class="card-title">About Me!</span>
                    <p>Something About Student</p>
                  </div>
                </div>
                <!-- Profile About  -->

                <!-- Profile About Details  -->
                <ul id="profile-page-about-details" class="collection z-depth-1">
                  <li class="collection-item">
                    <div class="row">
                      <div class="col s5 grey-text darken-1"><i class="mdi-action-wallet-travel"></i> E-mail</div>
                      <div class="col s7 grey-text text-darken-4 right-align">{{ object.Email }}</div>
                    </div>
                  </li>
                  <li class="collection-item">
                    <div class="row">
                      <div class="col s5 grey-text darken-1"><i class="mdi-social-poll"></i> Contact Number</div>
                      <div class="col s7 grey-text text-darken-4 right-align">{{ object.ContactNumber }}</div>
                    </div>
                  </li>

                </ul>
                <!--/ Profile About Details  -->


                <ul id="task-card" class="collection with-header">
                  <li class="collection-header orange">
                      <a href="#" class="white-text large">Recent Announcements For You</a>
                  </li>
                    {% for message in all_messages %}
                  <li class="collection-item ">
                      <input type="checkbox" id="task1" />
                      <label class="truncate" for="task1">{{ message.title }} <a href="#" class="secondary-content"><span class="ultra-small">{{ message.DateTime|naturaltime }}</span></a>
                      </label>
                  </li>
                    {% endfor %}

                </ul>

                <!-- task-card -->
                <ul id="task-card" class="collection with-header">
                  <li class="collection-header cyan">
                      <h4 class="task-card-title">My Task</h4><hr>
                      <p class="task-card-date">
                        <script>
                        var dt = new Date();
                        document.write((("0"+dt.getDate()).slice(-2)) +"."+ (("0"+(dt.getMonth()+1)).slice(-2)) +"."+ (dt.getFullYear()) + " " + (("0"+dt.getHours()).slice(-2)) +":"+ (("0"+dt.getMinutes()).slice(-2)));
                        </script>
                      </p>

                  </li>
                  <li class="collection-item dismissable">
                      <input type="checkbox" id="task1" />
                      <label for="task1">Task1 <a href="#" class="secondary-content"><span class="ultra-small">Today</span></a>
                      </label>
                      <span class="task-cat teal">Tag</span>
                  </li>

                </ul>
                <!-- task-card -->

              </div>

                <!-- profile-page-wall -->
              <div id="profile-page-wall" class="col s12 m8">

                <!-- profile-page-wall-posts -->
                <div id="profile-page-wall-posts" class="row">
                  <div class="col s12">

                      <h3 class="light-blue-text">Ask your Queries Here!</h3>
                      <!-- post here -->
                      <div id="profile-page-wall-post" class="card">

                        <div class="card-content">
                          <form method="post" action="{% url 'query:QuestionAsk' %}">
                          {% csrf_token %}

                          <div class="row">
                              <div class="col s10">
                                    <div class="input-field">
                                        <input type="text" name="QuestionTitle" id="query" required>
                                        <label class="active" for="query">Your Query?</label>
                                    </div>

                                  <div class="input-field" id="select1">

                                    <select aria-required="true" class="browser-default" name="CreatedFor" id="CreatedFor" required>

                                    <option value="" disabled selected>To whom it is concerned</option>

                                        {% for teacher in all_teachers %}
                                        <option value={{ teacher.FacultyID }}>{{ teacher.Name }}</option>
                                        {% endfor %}


                                    </select>

                                  </div>
                              </div>
                          <div class="s2 center vertical" style="top: 5vh; position: relative">
                              <button id="submit" class="btn large waves-effect waves-light">Ask</button>
                          </div>
                          </div>
                          </form>
                        </div>

                      </div>

                  </div>
                      <!--/post here -->

                </div>
              <h3 class="orange-text">Response to your previous queries</h3>
              <div class="content">
                  {% if Responses %}
                      {% for response in Responses %}
                          {% if forloop.counter < 6 %}
                          <div id="profile-page-wall-post" class="card">

                                <div class="card-content">
                                  <h5 class="orange-text"><span class="blue-grey-text darken-2">{{ forloop.counter }}. Query-</span> {{ response.Question.QuestionTitle }}</h5>
                                    <hr>
                                    <h6 class="light-blue-text"><span class="blue-grey-text">Response-</span> {{ response.AnswerTitle }}</h6>
                                </div>

                          </div>
                          {% endif %}
                  {% endfor %}
                      {% else %}
                      <h5> No Responses Yet!</h5>
                  {% endif %}
              </div>
                <!--/ profile-page-wall-posts -->

              </div>
              <!--/ profile-page-wall -->

            </div>


          </div>

          </div>


        <!-- Modal Structure -->
        <div id="modal1" class="modal">
            <div class="modal-content">
              <h4>FILL THE COURSES YOU HAVE IN THIS SEMESTER</h4>
              {{ form }}
            </div>
            <div class="modal-footer">
              <a href="#!" class="modal-close waves-effect waves-green btn-flat">Submit</a>
            </div>
        </div>


{% endblock %}

{% block js %}

    <script src="{% static 'js/studenthome.js' %}"></script>

{% endblock %}

source/templates/accounts/main.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Patrick+Hand+SC" rel="stylesheet">

{% endblock %}

{% block main %}


    <div class="container-fluid">
        {% if not request.user.is_authenticated %}
        <div class="row center-align teal lighten-1" id="section1">
            <div class="col s4 offset-s4" >
                <div class="transparent" id="first-section">

                <a style="margin-right: 10px " href="{% url 'accounts:login' %}" class="waves-effect waves-light btn-large light-blue"><i class="material-icons left">account_circle</i>LOGIN</a>
                <a href="{% url 'accounts:signup' %}"class="waves-effect waves-light btn-large orange"><i class="material-icons right">add_circle_outline</i>SIGN UP</a>
                </div>
            </div>
        </div>
        {% endif %}
    <div class="parallax1"></div>

    <div class="row center-align teal lighten-1" id="second-section">
        <div class="col s4 offset-s2" id="text1">

        Notification-System is a project which will help faculty to intimidate students about any important information
        like Schedule Changes, any upcoming seminar and other information. This information will be shared through SMS.
        </div>

        <div class="col s3 offset-s1" id="image">
            <img src="{% static 'Images/message.jpg' %}" class="responsive-img">
        </div>
    </div>

    <div class="parallax2"></div>
    </div>


{% endblock %}