source/Notification_System/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from source.accounts import urls as accounts_urls
from source.query import urls as query_urls
from source.Notification import urls as notification_urls


urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^query/', include(query_urls)),
    url(r'^notification/', include(notification_urls)),
    url(r'^main/$', TemplateView.as_view(template_name='accounts/main.html'), name='main'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name="contact"),
    url(r'^about/$', TemplateView.as_view(template_name='About.html'), name="about"),

    ]

source/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [

    url(r'login/$', views.LoginView , name="login"),
    url(r'signup/$', views.SignUpView , name="signup"),
    url(r'profile/$', views.ProfileView , name="profile"),
    url(r'logout/$', views.LogoutView , name="logout"),
]

source/query/urls.py
from django.conf.urls import url
from source.query.views import QuestionHandlingView, AnswerHandlingView

app_name = "query"

urlpatterns = [
    url(r'ask/$' , QuestionHandlingView, name="QuestionAsk"),
    url(r'answer/$' , AnswerHandlingView, name="QuestionAnswer")
]

source/templates/About.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

    <div class="row">
    <div class="col s3">

    <div class="card">

        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{% static 'Images/landscape.jpg' %}">
        </div>

        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">Card Title<i class="material-icons right">more_vert</i></span>
          <p><a href="#">This is a link</a></p>
        </div>

        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
          <p>Here is some more information about this product that is only revealed once clicked on.</p>
        </div>

    </div>
    </div>
    </div>

{% endblock %}

source/templates/Contact.html
{% extends 'base.html' %}
{% load static %}

{% block style %}

    <link rel="stylesheet" href="{% static 'css/contact.css' %}">

{% endblock %}
{% block main %}

    <div class="container-fluid">
        <div class="center-align" style="top: 35%;position: relative">
            <h2 class="white-text"><strong style="font-weight: 900; ">DEVELOPERS</strong> TEAM</h2>
        </div>
    </div>

    <br>

    <div class="row">

      <div class="col m4 offset-m2 s12">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
            <div class="flipper">
                <div class="front">
                  <div class="row">
                    <div class="col s12 m12">
                          <div class="card brown darken-1">
                            <div class="card-image">
                              <img src="{% static 'Images/madhav.jpg' %}">
                              <span class="card-title">Madhav Pruthi</span>
                            </div>
                            <div class="card-content white-text">
                              <p>Punjab Engineering College</p>
                            </div>
                          </div>
                    </div>
                    </div>
                </div>
                <div class="back">
                      <div class="row">
                        <div class="col s12">
                          <div class="card white">
                            <div class="card-content black-text">
                              <span class="card-title light-blue-text" style="font-weight: bold;font-size: 30px">About Me!</span>
                                <div class="orange-text">
                                <p>B.Tech 3rd Year</p>
                                <p>Computer Science</p>
                                <p>Contact: +91-9814471377</p>
                                <p>E-mail: madhavpruthi.becse16@pec.edu.in</p>
                                </div>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
      </div>

      <div class="col m4 offset-m2 s12">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
            <div class="flipper">
                <div class="front">
                  <div class="row">
                    <div class="col s12 m12">
                          <div class="card brown darken-1">
                            <div class="card-image">
                              <img src="{% static 'Images/img_5.jpg' %}">
                              <span class="card-title">Shreya Garg</span>
                            </div>
                            <div class="card-content white-text">
                              <p>Punjab Engineering College</p>
                            </div>
                          </div>
                    </div>
                    </div>
                </div>
                <div class="back">
                      <div class="row">
                        <div class="col s12">
                          <div class="card white">
                            <div class="card-content black-text">
                              <span class="card-title">About Me!</span>
                                <p>B.Tech 3rd Year</p>
                                <p>Contact: </p>
                                <p>E-mail</p>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
      </div>

      <div class="col m4 offset-m2 s12">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
            <div class="flipper">
                <div class="front">
                  <div class="row">
                    <div class="col s12 m12">
                          <div class="card brown darken-1">
                            <div class="card-image">
                              <img src="{% static 'Images/img_4.jpg' %}">
                              <span class="card-title">Guneet Bajaj</span>
                            </div>
                            <div class="card-content white-text">
                              <p>Punjab Engineering College</p>
                            </div>
                          </div>
                    </div>
                    </div>
                </div>
                <div class="back">
                      <div class="row">
                        <div class="col s12">
                          <div class="card white">
                            <div class="card-content black-text">
                              <span class="card-title">About Me!</span>
                                <p>B.Tech 3rd Year</p>
                                <p>Contact: </p>
                                <p>E-mail</p>
                            </div>
                          </div>
                        </div>
                      </div>
                </div>
            </div>
        </div>
      </div>

    </div>

{% endblock %}

{% block js %}

    <script>

        $(document).ready(function(){
            $('.parallax').parallax();
        });

     </script>

{% endblock %}

source/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>

    <meta name = "viewport" content = "width = device-width, initial-scale = 1">

    <link rel = "stylesheet" href = "https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel = "stylesheet"
     href = "{% static 'materialize/css/materialize.css' %}">

    <script src = "{% static 'materialize/js/jquery.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src = "{% static 'materialize/js/materialize.js' %}"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %} {% endblock %}</title>

    <style>
        .brand-logo p {
            font-size: 30px;
            margin-top: -1px;
            margin-left: 5px;
        }
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
          }

          main {
            flex: 1 0 auto;
          }
        footer.page-footer {
            padding-top: 0px;
          }
    </style>

    {% block style %}
    {% endblock %}


</head>

<body>

    <div class="navbar-fixed">
        <nav>
          <div class="nav-wrapper light-blue">
              &nbsp;<a href="{% url 'main' %}" class="brand-logo"><p>Notification System</p></a>
            <ul class="right hide-on-med-and-down">

              <li><a href="{% url 'about' %}">About</a></li>
              <li><a href="{% url 'contact' %}">Contact Us</a></li>
              {% if request.user.is_authenticated %}
                  <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                  <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              {% endif %}
            </ul>
          </div>
        </nav>
    </div>

    {% block main %}
    {% endblock %}

    <footer class="page-footer light-blue">
          <div class="footer-copyright">
            <div class="container">
            © 2018 Punjab Engineering College
            <a class="grey-text text-lighten-4 right" href="#!">Social links will come here</a>
            </div>
          </div>
    </footer>

    {% block js %}
    {% endblock %}



</body>
</html>